#This file stores configuration options for Paladin's Furniture Mod
#Sun Nov 26 01:56:22 CET 2023
chairsFacePlayer=true
checkForUpdates=true
countersOfDifferentMaterialsConnect=false
differentMirrorsConnect=false
enableBook=true
foodPopsOffStove=false
mobsSitOnChairs=true
renderImmersivePortalsMirrors=true
shaderSolidFix=false
spawnImmersivePortalsMirror=true
tablesOfDifferentMaterialsConnect=false
